name: Sync Issues from Teable

on:
  issues:
    types: [opened, edited, assigned, unassigned]  # 包括创建、编辑和分配/解除分配时触发
  issue_comment:
    types: [created, edited]  # 当评论创建或编辑时触发同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install psycopg2 requests python-dotenv

      - name: Run sync script
        run: python sync.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TRIGGER_ISSUE_ID: ${{ github.event.issue.number }}  # 动态传递 Issue ID
