name: Sync Issues from Teable

on:
  issues:
    types: [opened, edited, assigned, unassigned]  # 包括创建、编辑和分配/解除分配时触发
  issue_comment:
    types: [created, edited]  # 当评论创建或编辑时触发同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install psycopg2 requests python-dotenv

      # Step 4: Load environment variables from .env
      # - name: Load environment variables
      #  run: cat .env >> $GITHUB_ENV

      # Step 5: Run sync script
      - name: Run sync script
        run: python sync.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
